###############################
#                             #
#  NATS Server Configuration  #
#                             #
###############################
nats:
  # Server Tags
  serverTags:
    - "server"
  #mod: - "foo"
  # - "bar"

  # Toggle whether to enable external access.
  # This binds a host port for clients, gateways and leafnodes.
  #mod: externalAccess: false
  externalAccess: true

  # Toggle to disable client advertisements (connect_urls),
  # in case of running behind a load balancer
  # it might be required to disable advertisements.
  #mod: advertise: false
  advertise: false

  # In case both external access and advertise are enabled
  # then a service account would be required to be able to
  # gather the public ip from a node.
  serviceAccount:
    # Specifies whether a service account should be created
    create: true
    # Annotations to add to the service account
    annotations: {}
    # The name of the service account to use.
    # If not set and create is true, a name is generated using the fullname template
    #mod: name: ""
    name: "nats-server"

  jetstream:
    #mod: enabled: false
    enabled: true

    #############################
    #                           #
    #  Jetstream Memory Storage #
    #                           #
    #############################
    memStorage:
      enabled: true
      #mod: size: 1Gi
      size: 500Mi

    ############################
    #                          #
    #  Jetstream File Storage  #
    #                          #
    ############################
    fileStorage:
      enabled: true
      storageDirectory: /data

      # Set for use with existing PVC
      # existingClaim: jetstream-pvc
      # claimStorageSize: 10Gi

      # Use below block to create new persistent volume
      # only used if existingClaim is not specified
      #mod: size: 10Gi
      size: 2Gi
      # storageClassName: ""
      accessModes:
        - ReadWriteOnce
      annotations:
      # key: "value"

cluster:
  #mod: enabled: false
  enabled: false
  replicas: 1
  #mod: noAdvertise: false
  noAdvertise: true

# Authentication setup
auth:
  #mod: enabled: false
  enabled: true

  # basic:
  #   noAuthUser:
  #   # List of users that can connect with basic auth,
  #   # that belong to the global account.
  #   users:

  #   defaultPermissions:
  #     publish: ["SANDBOX.*"]
  #     subscribe: ["SANDBOX.>"]

  #   # List of accounts with users that can connect
  #   # using basic auth.
  #   accounts:

  # Reference to the Operator JWT.
  # operatorjwt:
  #   configMap:
  #     name: operator-jwt
  #     key: KO.jwt

  # Token authentication
  #mod: # token:
  token: YOUR_SECRET_TOKEN

